### ISSUE TITLE
How to encript auth cookie back

### ISSUE THREAD

**Issue by Gruski** [julian-maughan/FormsAuthDecryptor#1]
So using your decryptor from ASP.NET core app to decode an auth cookie created by my legacy WinForms app. This allows me to reuse the authentication created in my legacy app and reuse it in core app. The problem is that I need to advance the sliding expiration of the auth cookie forward so person is not automatically signed off if inactive on legacy app for more than 20min but active on core app. To do this I must rewrite the decoded auth cookie with new expiration datetime. How do I do this? Would I need an Encrypt function for that? If so do you have something like this or planing to add such a feature?

**Comment by julian-maughan** [comment]
Sorry I'm not planning to add encryption. I'd suggest using the Forms Auth auth token created by your legacy WinForms app as proof of identity, but then create a new 'session' using currently supported ASP.NET security options. You probably don't want to tie your .NET core app to Forms Auth anyway.
